services:
  boiler-plate: # サービス名
    container_name: boiler-plate
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./docker-golang/Dockerfile
    volumes: # マウントディレクトリ
      - ./boiler-plate:/go/src/boiler-plate
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./docker-golang/.go_env
    environment:
      - TZ=Asia/Tokyo
